### ISSUE TITLE
switch to sphinx-gallery

### ISSUE THREAD

**Issue by jschueller** [adutfoy/otECLM#7]
instead of nbsphinx, this is old tech

**Comment by adutfoy** [comment]
There is no example of sphinx-gallery example in the template. Once I have converted eclm.ipynb into plot_eclm.py and removed the reference to eclm.ipynb in example.rst, what do I have to do?

**Comment by jschueller** [comment]
look at how sofiane updated it:
https://github.com/sofianehaddad/ottemplatepython/commit/5c062c31873f36e1dc7662c07c594ab555500c37

**Comment by adutfoy** [comment]
Done (with pain!)

**Comment by jschueller** [comment]
great!, at least this adds some kind of testing
